# Generated by Django 5.2.10 on 2026-01-22 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package_name', models.CharField(max_length=100)),
                ('event_date', models.DateField()),
                ('event_location', models.CharField(max_length=100)),
                ('event_type', models.CharField(max_length=100)),
                ('attendees', models.PositiveIntegerField()),
                ('requirements', models.TextField(blank=True)),
                ('full_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=20)),
                ('company', models.CharField(blank=True, max_length=100)),
                ('agree_terms', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
