# Generated by Django 5.2.10 on 2026-01-30 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('event_date', models.DateField()),
                ('event_type', models.CharField(max_length=100)),
                ('event_location', models.CharField(max_length=255)),
                ('package_name', models.CharField(max_length=100)),
                ('attendees', models.IntegerField()),
                ('requirements', models.TextField(blank=True, null=True)),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'db_table': 'Book',
            },
        ),
    ]
