# Generated by Django 5.2.10 on 2026-01-30 11:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_form', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='book',
            table='book',
        ),
    ]
