# Generated by Django 5.2.10 on 2026-01-30 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_form', '0002_alter_book_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='agree_terms',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='book',
            name='company',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
