# Generated by Django 5.2.10 on 2026-01-19 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=100)),
                ('EventDate', models.DateField()),
                ('Email', models.EmailField(max_length=254, unique=True)),
                ('Message', models.TextField()),
            ],
            options={
                'db_table': 'Client',
            },
        ),
    ]
