# Generated by Django 5.2.10 on 2026-01-22 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('margret', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client',
            old_name='Email',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='EventDate',
            new_name='eventDate',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Message',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='client',
            old_name='Name',
            new_name='name',
        ),
    ]
